services:
    mockboard_dev:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - MBD_STORE_PATH=/backend/data/mockboard.db
        ports:
            - "8888:8000"
        volumes:
            - mockboard-data:/backend/data
        restart: unless-stopped

volumes:
    mockboard-data:
