server:
    port: ${PORT:8000}
    tomcat:
        threads:
            max: 500
            min-spare: 10

spring:
    application:
        name: mockboard
    main:
        banner-mode: off
    profiles:
        active: ${ACTIVE_PROFILE:default}
    threads:
        virtual:
            enabled: ${VI_THREADS:true}
